import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../state/app_state.dart';
import '../../theme/app_theme.dart';

class PetLinkScreen extends StatefulWidget {
  const PetLinkScreen({super.key});

  @override
  State<PetLinkScreen> createState() => _PetLinkScreenState();
}

class _CheckCodeForm extends StatefulWidget {
  const _CheckCodeForm();

  @override
  State<_CheckCodeForm> createState() => _CheckCodeFormState();
}

class _CheckCodeFormState extends State<_CheckCodeForm> {
  final _formKey = GlobalKey<FormState>();
  final _codeController = TextEditingController();
  bool _isLoading = false;

  @override
  void dispose() {
    _codeController.dispose();
    super.dispose();
  }

  void _submit() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() {
      _isLoading = true;
    });

    final state = Provider.of<AppState>(context, listen: false);
    final success = await state.linkPet(_codeController.text.trim());

    setState(() {
      _isLoading = false;
    });

    if (mounted) {
      if (success) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text("Pet link accepted successfully! Your pet is now added."),
            backgroundColor: Colors.green,
          ),
        );
        Navigator.pop(context);
      } else {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text("Invalid link code. Please verify and try again."),
            backgroundColor: Colors.redAccent,
          ),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Form(
      key: _formKey,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          TextFormField(
            controller: _codeController,
            decoration: const InputDecoration(
              labelText: "Enter Pet Link Code",
              hintText: "e.g. CODE-1234",
              prefixIcon: Icon(Icons.qr_code_rounded),
            ),
            validator: (value) {
              if (value == null || value.trim().isEmpty) {
                return "Please enter a code";
              }
              return null;
            },
          ),
          const SizedBox(height: 20),
          _isLoading
              ? const Center(child: CircularProgressIndicator())
              : ElevatedButton.icon(
                  onPressed: _submit,
                  icon: const Icon(Icons.link_rounded),
                  label: const Text("Accept Pet Link"),
                ),
        ],
      ),
    );
  }
}

class _PetLinkScreenState extends State<PetLinkScreen> {
  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final isDark = theme.brightness == Brightness.dark;

    return Scaffold(
      appBar: AppBar(
        title: const Text("Link Shop Pet"),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Container(
              padding: const EdgeInsets.all(20),
              decoration: BoxDecoration(
                color: AppTheme.orangePrimary.withOpacity(0.12),
                shape: BoxShape.circle,
              ),
              child: const Icon(
                Icons.add_link_rounded,
                size: 64,
                color: AppTheme.orangePrimary,
              ),
            ),
            const SizedBox(height: 24),
            Text(
              "Connect Partnered Shop Pet",
              style: theme.textTheme.headlineSmall?.copyWith(
                fontWeight: FontWeight.bold,
                color: isDark ? Colors.white : const Color(0xFF3E2723),
              ),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 12),
            Text(
              "If you bought your pet from a partnered pet shop, enter the link code generated by the shop admin to sync the pet profile, checklist milestones, and sale-time notes.",
              style: TextStyle(
                fontSize: 14,
                color: isDark ? Colors.white70 : Colors.black54,
                height: 1.4,
              ),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 30),
            const _CheckCodeForm(),
          ],
        ),
      ),
    );
  }
}
